spring:
  application:
    name: raidcomp-api
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: ${JDBC_URL:jdbc:mysql://root:root@localhost:3306/raidcomp}

server:
  forward-headers-strategy: native
  tomcat:
    remoteip:
      trusted-proxies: ${TRUSTED_PROXIES:}

wowaudit:
  keys: ${WOWAUDIT_API_KEY:key}

turnstile:
  secretKey: ${TURNSTILE_SECRET_KEY:1x0000000000000000000000000000000AA}

build:
  import:
    allowedIpRange: ${BUILD_IMPORT_ALLOWED_IP_RANGE:127.0.0.1}
