name = "raidcomp"
main = "src/index.ts"
compatibility_date = "2023-01-06"
route = "raidcomp.uk/*"
usage_model = "bundled"
workers_dev = false

[vars]
API_URL = "https://raidcomp-api.stefanpuia.co.uk"
FRONTEND_URL = "https://raid-comp.pages.dev/"

[env.dev]
name = "raidcomp-dev"
route = "dev.raidcomp.uk/*"
vars = { FRONTEND_URL="http://localhost:3000", API_URL="http://localhost:8080", API_KEY="test-key" }

[env.production]
vars = { FRONTEND_URL="https://raid-comp.pages.dev/", API_URL="https://raidcomp-api.stefanpuia.co.uk" }

[triggers]
crons = [ ]
