name = "raidcomp"
main = "src/index.ts"
compatibility_date = "2023-01-06"
route = "raidcomp.uk/*"
workers_dev = false

[env.dev]
route = "dev.raidcomp.uk/*"
vars = { FRONTEND_URL="https://dev.raid-comp.pages.dev/", API_URL="https://apim-raidcomp.azure-api.net/dev" }

[env.production]
vars = { FRONTEND_URL="https://raid-comp.pages.dev/", API_URL="https://apim-raidcomp.azure-api.net/prod" }
