parameters:
  - name: environment
  - name: containerName
  - name: containerPort

stages:
  - stage: deploy_env_${{ parameters.environment }}
    displayName: Deploy ${{ parameters.environment }}
    dependsOn: buildAndPackage
    jobs:
      - deployment: deploy_env_${{ parameters.environment }}
        pool: self-hosted-scale-set-02
        environment: ${{ parameters.environment }}
        variables:
          - group: deploy-${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  displayName: Login to ACR
                  inputs:
                    command: login
                    containerRegistry: $(dockerRegistryServiceConnection)

                - script: docker pull $(dockerRegistry)/$(dockerImage):$(dockerImageVersion)
                  displayName: Pull image

                - task: Docker@2
                  displayName: Docker Logout
                  inputs:
                    command: logout
                    containerRegistry: $(dockerRegistryServiceConnection)
                  condition: always()

                - script: docker rm -f ${{ parameters.containerName }}
                  displayName: Remove existing container

                - script: |
                    docker run -d \
                      --name ${{ parameters.containerName }} \
                      --restart always \
                      --add-host=host.docker.internal:host-gateway \
                      -p ${{ parameters.containerPort }}:8080 \
                      -e PORT \
                      -e JDBC_URL \
                      $(dockerRegistry)/$(dockerImage):$(dockerImageVersion)
                  displayName: Start container
                  env:
                    PORT: 8080
                    JDBC_URL: $(database-url)
