parameters:
  - name: environment
  - name: dependsOn

stages:
  - stage: deploy_env_${{ parameters.environment }}
    displayName: Deploy ${{ parameters.environment }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - deployment: deploy_env_${{ parameters.environment }}
        pool: self-hosted-scale-set-02
        environment: ${{ parameters.environment }}
        variables:
          - group: deploy-${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  displayName: Login to ACR
                  inputs:
                    command: login
                    containerRegistry: $(dockerRegistryServiceConnection)

                - script: docker pull $(dockerRegistry)/$(dockerImage):$(dockerImageVersion)
                  displayName: Pull image

                - task: Docker@2
                  displayName: Docker Logout
                  inputs:
                    command: logout
                    containerRegistry: $(dockerRegistryServiceConnection)
                  condition: always()

                - script: docker rm -f $(containerName)
                  displayName: Remove existing container

                - script: |
                    docker run -d \
                      --name $(containerName) \
                      --restart always \
                      --add-host=host.docker.internal:host-gateway \
                      -p $(containerPort):8080 \
                      -e PORT \
                      -e JDBC_URL \
                      -e WOWAUDIT_API_KEY \
                      -e TURNSTILE_SECRET_KEY \
                      $(dockerRegistry)/$(dockerImage):$(dockerImageVersion)
                  displayName: Start container
                  env:
                    PORT: 8080
                    JDBC_URL: $(database-url)
                    WOWAUDIT_API_KEY: $(WOWAUDIT_API_KEY)
                    TURNSTILE_SECRET_KEY: $(TURNSTILE_SECRET_KEY)
