pr: none

trigger:
  paths:
    include:
      - api

variables:
  isMain: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  gradleCacheVersion: v1
  workingDirectory: $(Build.SourcesDirectory)/api

stages:
  - stage: buildAndPackage
    displayName: Check
    jobs:
      - job: checkAndPackage
        displayName: Check
        steps:
          - task: JavaToolInstaller@0
            displayName: Set java version to 21
            inputs:
              versionSpec: '21'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          - task: Cache@2
            inputs:
              key: '"$(gradleCacheVersion)" | "gradle" | "$(Agent.OS)" | $(workingDirectory)/**/build.gradle'
              restoreKeys: |
                "$(gradleCacheVersion)" | "gradle" | "$(Agent.OS)"
                "$(gradleCacheVersion)" | "gradle"
                "$(gradleCacheVersion)"
              path: $(GRADLE_USER_HOME)
            displayName: Configure gradle caching

          - task: Gradle@3
            displayName: Gradle Build
            inputs:
              options: '--build-cache -Duser.language=en -Duser.country=GB'
              tasks: 'clean bootJar'
              testResultsFiles: '**/TEST-*.xml'
              publishJUnitResults: true
              gradleWrapperFile: $(workingDirectory)/gradlew
              workingDirectory: $(workingDirectory)

          # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
          - script: |
              ./gradlew --stop
            displayName: Stop the Gradle daemon
            workingDirectory: $(workingDirectory)

          - ${{ if eq(variables.isMain, true) }}:
              - task: PublishBuildArtifacts@1
                displayName: Publish Artifacts
                inputs:
                  pathToPublish: '$(workingDirectory)/build/libs'
                  artifactName: drop

  - ${{ if eq(variables.isMain, true) }}:
      - stage: deployProd
        displayName: Deploy Prod
        dependsOn: buildAndPackage
        jobs:
          - deployment: deployProd
            environment:
              name: prod
              resourceType: VirtualMachine
            strategy:
              runOnce:
                deploy:
                  steps:
                    - download: none

                    - task: DownloadBuildArtifacts@1
                      inputs:
                        artifactName: drop
                        downloadPath: $(System.ArtifactsDirectory)

                    - script: |
                        set -e
                        sudo systemctl stop raidcomp.service
                        sudo mv $(System.ArtifactsDirectory)/drop/raidcomp-api.jar /app/raidcomp-api.jar
                        sudo chown raidcomp:raidcomp /app/raidcomp-api.jar
                        sudo systemctl enable --now raidcomp.service
