swagger:
  outputDirectory: ./dist
  entryFile: 
    - ./src/controller/*
  outputFormat: OpenApi_3
  name: Raid Composition API
  license: MIT
  produces: [application/json]
  version: 1.0.0
  # securityDefinitions:
  #   default:
  #     type: apiKey
  #     in: header
  #     name: Authorization
  #   secondAuthenticator:
  #     type: apiKey
  #     in: header
  #     name: Authorization
